### ISSUE TITLE
Vock fails to build on OSX 10.8

### ISSUE THREAD

**Issue by sandfox** [indutny/vock#1]
When installing via npm with `sudo npm install -g vock` i get the following errors back from clang

``` shell
In file included from ../src/audio/au.cc:1:
../src/audio/au.h:81:3: error: unknown type name 'uv_mutex_t'
  uv_mutex_t in_mutex_;
  ^
../src/audio/au.h:82:3: error: unknown type name 'uv_mutex_t'
  uv_mutex_t out_mutex_;
  ^
2 errors generated.
```

Running Mountain Lion (please don't hate me), if I get some time i'll have a look at the code but no promises.

**Comment by sandfox** [comment]
Annnddd I'm a muppet, was running node `v0.6.18`, upgrading to `v0.8.4` made everything better.
Is it worth specifying the minimum engine required in the `package.json`?

**Comment by indutny** [comment]
You're right, fixed f0847d46d0f9256a977a14d0ac1abd2d8ceca275
